import json, numpy as np, mpmath as mp, matplotlib
matplotlib.use('Agg'); import matplotlib.pyplot as plt
plt.rcParams.update({'font.size':10,'axes.grid':True,'grid.alpha':0.3})
H=json.load(open('hazard_spec.json')); C=json.load(open('clockgrid.json'))['rows']
ts=np.array([r[0] for r in H['rows']]); fs=np.array([float(mp.mpf(r[1])) for r in H['rows']]); Ss=np.array([float(mp.mpf(r[2])) for r in H['rows']]); hs=np.array([float(mp.mpf(r[3])) for r in H['rows']])
tc=np.array([r['t'] for r in C]); fc=np.array([float(mp.mpf(r['f'])) for r in C]); Sc=np.array([float(mp.mpf(r['S'])) for r in C])
fig,ax=plt.subplots(1,3,figsize=(10,3.3))
m=ts<=0.08
ax[0].plot(ts[m],fs[m],color='navy',lw=1.5,label='spectral (Kent)')
ax[0].plot(tc[tc<=0.08],fc[tc<=0.08],'o',ms=2.5,color='darkorange',label='Talbot (Pólya)')
ax[0].set_xlabel('t'); ax[0].set_title('density of the clock'); ax[0].legend(fontsize=7)
ax[1].semilogy(ts,Ss,color='crimson'); ax[1].semilogy(tc[tc<=0.4],np.maximum(Sc[tc<=0.4],1e-30),'.',ms=3,color='teal')
ax[1].set_xlabel('t'); ax[1].set_title('survival P(T>t)')
g1=float(mp.mpf(H['g'][0])**2)
ax[2].semilogy(ts[ts>=0.02],np.abs(hs[ts>=0.02]-g1)+1e-22,color='purple')
ax[2].semilogy(ts[ts>=0.02],0.5*np.exp(-242.1357*(ts[ts>=0.02]-0.05)),'--',color='gray',lw=0.9,label=r'slope $-(\gamma_2^2-\gamma_1^2)$')
ax[2].set_xlabel('t'); ax[2].set_title(r'$|h(t)-\gamma_1^2|$'); ax[2].legend(fontsize=7)
fig.tight_layout(); fig.savefig('fig/clocklaw.pdf'); plt.close()
R=json.load(open('rsboundary.json')); M=json.load(open('mc.json'))
fig,ax=plt.subplots(1,2,figsize=(9,3.4))
T=np.array(R['t']); B=np.array(R['b']); BE=np.array(R['beta'])
ax[0].plot(T,B,color='darkgreen',lw=1.6,label='boundary b(t)')
ax[0].plot(T,0.42-np.sqrt(2)*14.134725*T,'--',color='gray',lw=0.9,label=r'slope $-\sqrt{2}\gamma_1$')
ax[0].set_xlabel('t'); ax[0].legend(fontsize=8); ax[0].set_title('Roberts Shortland tangent boundary')
ax[1].plot(M['grid'],M['Ft'],color='black',lw=1.4,label='clock CDF (exact)')
ax[1].plot(M['grid'],M['Fe'],color='orangered',lw=1,ls='--',label='Brownian crossing, Monte Carlo')
ax[1].set_xlabel('t'); ax[1].legend(fontsize=8); ax[1].set_title('KS distance %.4f, n = %d'%(M['ks'],M['n']))
fig.tight_layout(); fig.savefig('fig/rsboundary.pdf'); plt.close()
print('ok')
