import json, numpy as np, matplotlib
matplotlib.use('Agg'); import matplotlib.pyplot as plt
plt.rcParams.update({'font.size':10,'axes.grid':True,'grid.alpha':0.25,'axes.spines.top':False,'axes.spines.right':False})
S=json.load(open('sens.json')); Tw=json.load(open('twisted.json'))
fig,ax=plt.subplots(1,3,figsize=(12.5,3.5))
a=Tw['amp']; ax[0].semilogy(a['g'],a['plain'],'.',ms=3,color='#1b4f72',label=r'Riesz: $|\Gamma(1-\rho/2)/2\zeta^\prime(\rho)|$')
ax[0].semilogy(a['g'],a['tw'],'.',ms=3,color='#c0392b',label=r'twisted, $T=50$: $|\Gamma(1-\rho/2+iT)/2\zeta^\prime(\rho)|$')
ax[0].set_xlabel(r'ordinate $\gamma$'); ax[0].set_ylim(1e-80,10); ax[0].legend(fontsize=6.5); ax[0].set_title('Which zeros a Riesz filter sees',fontsize=9)
s=Tw['series']; x=np.array(s['x'])
ax[1].semilogx(x,np.array(s['re'])/x**0.25,'o',ms=3,color='#1b4f72',label=r'$\mathrm{Re}\,R_T(x)/x^{1/4}$, M\"obius series')
ax[1].semilogx(x,np.array(s['pre'])/x**0.25,color='#c0392b',lw=0.8,label='explicit formula over 300 zeros')
ax[1].set_xlabel('x'); ax[1].legend(fontsize=6.5); ax[1].set_title(r'Twisted Riesz function, $T=50$',fontsize=9)
M=S['margins']; k=[float(q) for q in M]
ax[2].plot(k,[M[q]['zeta'][1] for q in M],'o-',color='#1b4f72',label='zeta zeros, 1% quantile')
ax[2].plot(k,[M[q]['cue'][1] for q in M],'s--',color='#c0392b',label='CUE, 1% quantile')
ax[2].plot(k,[M[q]['zeta'][3] for q in M],'o-',color='#1b4f72',alpha=0.4,label='zeta zeros, median')
ax[2].plot(k,[M[q]['cue'][3] for q in M],'s--',color='#c0392b',alpha=0.4,label='CUE, median')
ax[2].set_xlabel(r'resolution $\kappa$ (mean spacings)'); ax[2].set_ylabel('normalised density at midpoints'); ax[2].legend(fontsize=6.5); ax[2].set_title('Positivity margins against random matrix theory',fontsize=9)
fig.tight_layout(); fig.savefig('fig_strategy.pdf'); print('ok')

# the book splits this figure: the two Riesz panels (Chapter ch:riesz) and the margin panel (Chapter ch:almost)
def riesz_panels(ax0,ax1):
    ax0.semilogy(a['g'],a['plain'],'.',ms=3,color='#1b4f72',label=r'Riesz: $|\Gamma(1-\rho/2)/2\zeta^\prime(\rho)|$')
    ax0.semilogy(a['g'],a['tw'],'.',ms=3,color='#c0392b',label=r'twisted, $T=50$: $|\Gamma(1-\rho/2+iT)/2\zeta^\prime(\rho)|$')
    ax0.set_xlabel(r'ordinate $\gamma$'); ax0.set_ylim(1e-80,10); ax0.legend(fontsize=6.5); ax0.set_title('Which zeros a Riesz filter sees',fontsize=9)
    ax1.semilogx(x,np.array(s['re'])/x**0.25,'o',ms=3,color='#1b4f72',label=r'$\mathrm{Re}\,R_T(x)/x^{1/4}$, M\"obius series')
    ax1.semilogx(x,np.array(s['pre'])/x**0.25,color='#c0392b',lw=0.8,label='explicit formula over 300 zeros')
    ax1.set_xlabel('x'); ax1.legend(fontsize=6.5); ax1.set_title(r'Twisted Riesz function, $T=50$',fontsize=9)
fig,ax=plt.subplots(1,2,figsize=(9,3.5)); riesz_panels(ax[0],ax[1])
fig.tight_layout(); fig.savefig('fig_filters.pdf'); plt.close(fig)
fig,ax2=plt.subplots(1,1,figsize=(5,3.5))
ax2.plot(k,[M[q]['zeta'][1] for q in M],'o-',color='#1b4f72',label='zeta zeros, 1% quantile')
ax2.plot(k,[M[q]['cue'][1] for q in M],'s--',color='#c0392b',label='CUE, 1% quantile')
ax2.plot(k,[M[q]['zeta'][3] for q in M],'o-',color='#1b4f72',alpha=0.4,label='zeta zeros, median')
ax2.plot(k,[M[q]['cue'][3] for q in M],'s--',color='#c0392b',alpha=0.4,label='CUE, median')
ax2.set_xlabel(r'resolution $\kappa$ (mean spacings)'); ax2.set_ylabel('normalised density at midpoints'); ax2.legend(fontsize=6.5)
fig.tight_layout(); fig.savefig('fig_margins.pdf'); print('ok split')
