"""RECONSTRUCTION, NOT THE AUTHORS' CODE.

Compute stage of an attempt to regenerate data/results_main.json, which no script in the
archive writes (neither code/primeside.py nor code/plots.py; nothing reads it either). The
file holds, for eps in 0.5, 0.2, 0.1, 0.05, 0.02, 0.01, the Thorin density
rho_eps(theta) = Re(xi'/xi)(1/2 + eps + i theta)/pi on 0 <= theta <= B = 58 (step eps/16,
npts = 16 B/eps + 1) compared with the Poisson sum over the first N = 1700 ordinates
(T = gamma_1700), with and without a tail model, and the masses of the cells around the
12 ordinates below 58. This stage evaluates everything that is expensive once, following
the conventions of code/part2.py and code/analyse.py (polya_flint setup(420, 200, 3),
continuous argument from np.angle of successive ratios, zero sums in long double), and saves
the arrays; main_analyse.py then tries candidate definitions of the fields.
Usage: python main_compute.py EPS    (needs g_1_400.npy, g_401_1000.npy, g_1001_1700.npy,
       the zero lists regenerated by the earlier rerun with mpmath.zetazero at 30 digits)
Output: main_EPS.npz
"""
import sys, time
import numpy as np, mpmath as mp
from scipy import integrate
from scipy.interpolate import CubicSpline
from flint import acb
from polya_flint import setup, xi_pair

eps = float(sys.argv[1])
B = 58.0
gall = np.concatenate([np.load(f) for f in ['g_1_400.npy', 'g_401_1000.npy', 'g_1001_1700.npy']])
K = int(round(B / (eps / 16)))
th = np.linspace(0, B, K + 1)
S = setup(420, 200, 3)
t0 = time.time()
F = np.zeros(K + 1); A = np.zeros(K + 1); prev = None; acc = 0.0; mx = 0.0
for k in range(K + 1):
    a, b = xi_pair(S, acb(eps, th[k]))
    F[k] = float((b / a).real)
    v = complex(a)
    if prev is not None:
        d = np.angle(v / prev); mx = max(mx, abs(d)); acc += d
    prev = v; A[k] = acc
secs_polya = time.time() - t0
# Poisson sum over the first 1700 ordinates, with the reflected kernels, in long double and in double
thl = th.astype(np.longdouble); e = np.longdouble(eps)
Rld = np.zeros(K + 1, dtype=np.longdouble)
for g in gall.astype(np.longdouble):
    Rld += e / (e * e + (thl - g) ** 2) + e / (e * e + (thl + g) ** 2)
Rld = (Rld / np.longdouble(np.pi)).astype(float)
R64 = np.zeros(K + 1)
for g in gall:
    R64 += eps / (eps * eps + (th - g) ** 2) + eps / (eps * eps + (th + g) ** 2)
R64 = R64 / np.pi
# tail models: int_{T0}^oo [P(theta - t) + P(theta + t)] n(t) dt, P(x) = eps/(pi(eps^2 + x^2))
mp.mp.dps = 30
g1700 = float(gall[-1]); g1701 = float(mp.zetazero(1701).imag)
Tstar = float(mp.findroot(lambda T: mp.siegeltheta(T) / mp.pi + 1 - 1700, 2197.5))
dens = {'log': lambda t: np.log(t / (2 * np.pi)) / (2 * np.pi),
        'log48': lambda t: (0.5 * np.log(t / (2 * np.pi)) + 1 / (48 * t * t)) / np.pi}
starts = {'g1700': g1700, 'Tstar': Tstar, 'mid': 0.5 * (g1700 + g1701)}
c = np.linspace(0, B, 233)
tails = {}
for sn, T0 in starts.items():
    for dn, n in dens.items():
        v = []
        for t in c:
            q, _ = integrate.quad(lambda g: (eps / (eps ** 2 + (t - g) ** 2) + eps / (eps ** 2 + (t + g) ** 2)) / np.pi * n(g),
                                  T0, np.inf, epsabs=1e-16, epsrel=1e-12, limit=200)
            v.append(q)
        tails[f'tail_{sn}_{dn}'] = CubicSpline(c, v)(th)
np.savez(f'main_{eps}.npz', eps=eps, B=B, th=th, F=F, arg=A, maxstep=mx, Rld=Rld, R64=R64, secs_polya=secs_polya,
         g1700=g1700, g1701=g1701, Tstar=Tstar, gw=gall[gall < B], gnext=gall[np.sum(gall < B)], **tails)
print(eps, 'npts', K + 1, 'polya secs', round(secs_polya, 1), 'maxstep', mx, 'mass(arg)', A[-1] / np.pi, 'min rho', F.min() / np.pi, flush=True)
